package app.retvens.rown.NavigationFragments.eventForUsers.onGoingEvents

data class OnGoingEventsData(
    val booking_link: String,
    val category_id: String,
    val city: String,
    val country: String,
    val date_added: String,
    val email: String,
    val event_category: String,
    val event_description: String,
    val event_end_date: String,
    val event_end_time: String,
    val event_id: String,
    val event_start_date: String,
    val event_start_time: String,
    val event_thumbnail: String,
    val event_title: String,
    val location: String,
    val phone: String,
    val price: String,
    val registration_end_date: String,
    val registration_end_time: String,
    val registration_start_date: String,
    val registration_start_time: String,
    val state: String,
    val user_id: String,
    val User_name: String,
    val Profile_pic: String,
    val venue: String,
    val saved: String,
    val website_link: String
)